config/routes.rb
Rails.application.routes.draw do
  mount LetsencryptHttpChallenge::Engine => "/" unless ENV['LE_HTTP_CHALLENGE_RESPONSE'].blank?
  
  devise_for :users

  resources :article_bookmarks, only: [:index]

  root to: 'pages#home'

  resources :articles, only: [:index, :destroy]

  resources :topics do
    member do
      post :publish
    end
  end

  post 'topic_article', to: 'topic_articles#create'
  delete 'topic_article', to: 'topic_articles#destroy'

  post 'bookmark', to: 'article_bookmarks#create'
  delete 'bookmark', to: 'article_bookmarks#destroy'

  # Styleguide
  get 'styleguide', to:'pages#styleguide'

  get 'team', to: 'pages#team'

  get 'about', to: 'pages#about'

  # Test api aylien
  get 'search', to: 'aylien_tests#search'
  get 'results', to: 'aylien_tests#results'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/article.rb
class Article < ApplicationRecord
  OPPOSITE_MEDIA = {
    "Marianne" => ["La Tribune", "Le Figaro", "Valeurs Actuelles", "Les Echos", "Le Point", "L'Express", "La Croix", "Le Monde"],
    "Libération" => ["Les Echos", "La Croix", "L'Express", "Le Point", "Valeurs Actuelles" "Le Figaro", "La Tribune", "Le Monde"],
    "Médiapart" => ["Le Point", "L'Express",  "La Croix", "Valeurs Actuelles", "Le Figaro", "Les Echos", "La Tribune", "Le Monde"],
    "Le Monde" => ["Valeurs Actuelles", "Le Figaro", "La Tribune", "Les Echos", "L'Express", "La Croix", "Le Point"],
    "L'Express" => ["Marianne", "Médiapart", "Libération", "Le Monde"],
    "Le Point" => ["Médiapart", "Libération", "Marianne", "Le Monde"],
    "La Tribune" => ["Marianne", "Médiapart", "Libération", "Le Monde"],
    "Les Echos" => ["Libération", "Médiapart", "Marianne", "Le Monde"],
    "La Croix" => ["Libération", "Marianne", "Médiapart", "Le Monde"],
    "Le Figaro" => ["Médiapart", "Marianne", "Libération", "Le Monde"],
    "Valeurs Actuelles" => ["Le Monde", "Marianne", "Libération", "Médiapart"]
  }

  belongs_to :source
  # belongs_to :category
  belongs_to :journalist

  has_many :topic_articles, dependent: :destroy
  has_many :topics, through: :topic_articles
  has_many :article_bookmarks, dependent: :destroy

  def self.random_sort(articles)
    # FIXME revamp random_sort to have only recent articles from each sources

    random_articles = []

    sources_id = []

    articles.each do |article|
      random_articles << article unless sources_id.include? article.source
      sources_id << article.source unless sources_id.include? article.source
    end

    random_articles
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index ]

  OBSOLETE_TIME = 24 * 60 * 60

  def index
    # session[:current_search] = params
    @topic_search = params[:topic_search]

    if Topic.pluck(:name).include?(@topic_search)
      # 1. topic already exists
      @topic = Topic.find_by_name(@topic_search)
        if Time.now - Topic.find_by_name(@topic_search).articles.last.created_at > OBSOLETE_TIME
          # 1.1 topic updated more than 24h ago
            # new search
            @topic.new_search

            # display
            display_articles(@topic)
        else
          # 1.2 topic updated less than 24h ago
            # display existing articles (no new search)
            display_articles(@topic)
        end
    else
      # 2. topic doesn't exists
        # create topic
        @topic = Topic.new(name: @topic_search)
        @topic.user = User.find_by_email("search@hedgenews.eu")
        # new search
        @topic.new_search
        # display
        display_articles(@topic)
    end
  end

  def destroy
  end

  private

  def display_articles(topic)
    # FIXME is `reverse` usefull?
    @articles = topic.articles.sort_by {|article| article.created_at}.reverse
    # FIXME revamp random_sort
    @selected_articles = Article.random_sort(@articles)
  end

end

app/helpers/article_helper.rb
module ArticleHelper
  def time_to_read(words_count)
    time = words_count / 250
    if time < 1
      return "Moins d'une minute à lire"
    elsif time < 2
      return "Une minute à lire"
    else
      return "#{time} minutes à lire"
    end
  end

  def story_opposite_url(story, source_urls)
    source_name = Source.where(aylien_id: story.source.id.to_i).first.name

    opposite_media = Article::OPPOSITE_MEDIA[source_name]
    return unless opposite_media

    opposite_media.each do |opposite_medium|
      opposite_url = source_urls[opposite_medium]
      return opposite_url if opposite_url
    end

    return nil
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def time_to_read(words_count)
    time = words_count / 250
    if time < 1
      return "Moins d'une minute à lire"
    elsif time < 2
      return "Une minute à lire"
    else
      return "#{time} minutes à lire"
    end
  end

  # had to put that method in the articles controller
  def story_opposite_url(story, source_urls)
    source_name = Source.where(aylien_id: story.source.id.to_i).first.name

    opposite_media = Article::OPPOSITE_MEDIA[source_name]
    return unless opposite_media

    opposite_media.each do |opposite_medium|
      opposite_url = source_urls[opposite_medium]
      return opposite_url if opposite_url
    end

    return nil
  end

end

app/views/articles/_article_create.html.erb
<% if local_assigns[:story] %>
  <%= hidden_field_tag "article[source_id]", Source.where(aylien_id: story.source.id.to_i).first.id %>
  <%= hidden_field_tag "article[title]", story.title %>
  <% unless story.media[0].nil? %>
    <%= hidden_field_tag "article[pic_url]", story.media[0].url %>
  <% end %>
  <%= hidden_field_tag "journalist[aylien_id]", story.author.id %>
  <%= hidden_field_tag "journalist[last_name]", story.author.name %>
  <%= hidden_field_tag "article[date]", story.published_at %>
  <%= hidden_field_tag "article[abstract]", story.summary.sentences.join("\n") %>
  <%= hidden_field_tag "article[words_count]", story.words_count %>
  <%= hidden_field_tag "article[aylien_id]", story.id %>
  <%= hidden_field_tag "article[source_url]", story.links.permalink %>
  <%= hidden_field_tag "article[opposite_url]", story_opposite_url(story, @hash_source_url) %>
<% else %>
  <%= hidden_field_tag "article[source_id]", article.source_id %>
  <%= hidden_field_tag "article[title]", article.title %>
  <% unless article.pic_url.nil? %>
    <%= hidden_field_tag "article[pic_url]", article.pic_url %>
  <% end %>
  <%= hidden_field_tag "journalist[aylien_id]", article.journalist.aylien_id %>
  <%= hidden_field_tag "journalist[last_name]", article.journalist.last_name %>
  <%= hidden_field_tag "article[date]", article.date %>
  <%= hidden_field_tag "article[abstract]", article.abstract %>
  <%= hidden_field_tag "article[words_count]", article.words_count %>
  <%= hidden_field_tag "article[aylien_id]", article.aylien_id %>
  <%= hidden_field_tag "article[source_url]", article.source_url %>
  <%= hidden_field_tag "article[opposite_url]", article.opposite_url %>
<% end %>

app/views/articles/_bookmark_form.html.erb
<%= form_tag bookmark_path, method: :post, remote: true, id: 'article' do %>
  <div class='bookmark-parent'>
    <% if local_assigns[:story] %>
      <%= hidden_field_tag "article[aylien_id]", story.aylien_id %>
    <% else %>
      <%= hidden_field_tag "article[aylien_id]", article.aylien_id %>
    <% end %>
    <%= button_tag '', class: 'bookmark icon button-tag button-tag-bookmark' do %>
      <%= image_tag 'icone/bookmark_empty_blue.png' %>
    <% end %>
  </div>
<% end %>

app/views/articles/_unbookmark_form.html.erb
<%= form_tag bookmark_path, method: :delete, remote: true, id: 'article' do %>
  <div class='unbookmark-parent'>
    <% if local_assigns[:story] %>
      <%= hidden_field_tag "article[aylien_id]", story.aylien_id %>
    <% else %>
      <%= hidden_field_tag "article[aylien_id]", article.aylien_id %>
    <% end %>
    <%= button_tag '', class: 'unbookmark icon button-tag button-tag-bookmark' do %>
      <%= image_tag 'icone/bookmark_full_blue.png' %>
    <% end %>
  </div>
<% end %>

app/views/articles/index.html.erb
<% if @articles.nil? || @articles.empty? %>

  <div class='container'>
    <div class="flex-box-space-around catchline wrapper-white font-header-app">
      <div>
        <h2 class= "font-header-app">Aucun article trouvé pour <em><%= @topic_search %></em>.</h2>
        <h2 class= "font-header-app">Modifiez votre recherche :</h2>
      </div>
      <%= render 'shared/search_bar', value: @topic_search %>
    </div>
    <%= link_to root_path do %>
      <%= image_tag "icone/hedgenews_logo.FF682F.png", class: "animate-logo" %>
    <%end%>
  </div>

<% else %>
  <div class="container">
    <div class="flex-box-space-around font-header-app">
      <div id="search-wrapper" class="wrapper-white">
        <div>
          <h2 class="font-header-app"><%= pluralize(@selected_articles.count, 'article selectionné', plural: 'articles sélectionnés')%>  parmi <%= @articles.count %> pour <em><%= @topic_search %></em></h2>
        </div>
        <%= render 'shared/search_bar', value: @topic_search %>
      </div>
    </div>
    <div class="flex-box-center">
      <a href="#" class="btn btn-bordered btn-bordered-primary btn-bordered-primary-on-grey-background open-all">Lire tous les articles complets</a>
      <%= content_tag :div, class: "selected_urls", data: {url: @selected_urls} do %>
      <% end %>
      <%if current_user %>
        <%unless current_user.topics.include?(@topic) %>
          <%= form_tag topics_path, method: :post, id: 'topic' do %>
            <%= hidden_field_tag "topic[name]", @topic_search %>
            <%= submit_tag 'Ajouter le sujet à mes revues de presse', class: 'btn btn-bordered btn-bordered-info btn-bordered-info-on-grey-background' %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <br>
    <div class="flex-box-center" >
      <div id="search-wrapper">
        <%= render 'shared/index_articles', value: @selected_articles %>
      </div>
    </div>
  </div>

  <div class="container text-center">
    <%= link_to root_path do %>
      <%= image_tag "icone/rewind.FF682F.png", class: 'image-small' %>
    <% end %>
  </div>

<% end %>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function(){

      window.scroll(0, 60);

      $('#topic_search').click(function(){
        $(this).val("");
      });

      $('a.open-all').click(function(e) {
        e.preventDefault();
        $('.selected_urls').data('url').forEach(function(url_source) {
          setTimeout(function() {}, 1000);
          window.open(url_source);
          self.focus();
          // if(!win){
          //   //Broswer has blocked it
          //   alert('Please allow popups for this site');
          // }
        });
      });

      $('.press-review-title').click(function(e) {
        setTimeout(function() {}, 10);
        $(this).closest('.dropdown-menu').fadeOut('slow', function(){
          $(this).hide();
        });
      });

    });
  </script>
<% end %>