config/routes.rb
Rails.application.routes.draw do
  mount LetsencryptHttpChallenge::Engine => "/" unless ENV['LE_HTTP_CHALLENGE_RESPONSE'].blank?
  
  devise_for :users

  resources :article_bookmarks, only: [:index]

  root to: 'pages#home'

  resources :articles, only: [:index, :destroy]

  resources :topics do
    member do
      post :publish
    end
  end

  post 'topic_article', to: 'topic_articles#create'
  delete 'topic_article', to: 'topic_articles#destroy'

  post 'bookmark', to: 'article_bookmarks#create'
  delete 'bookmark', to: 'article_bookmarks#destroy'

  # Styleguide
  get 'styleguide', to:'pages#styleguide'

  get 'team', to: 'pages#team'

  get 'about', to: 'pages#about'

  # Test api aylien
  get 'search', to: 'aylien_tests#search'
  get 'results', to: 'aylien_tests#results'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :topic_articles, dependent: :destroy
  has_many :articles, through: :topic_articles
  belongs_to :user

  # Constants for Topic.get
  N_LATEST_STORIES = 5
  HASHTAGS_MIN_LENGTH = 5
  HASHTAGS_MAX_LENGTH = 20
  RELEVANCE_INDEX = 15
  OBSOLETE_TIME = 24 * 60 * 60

  # FIXME : really need to do that ?
  # before_update :update_sources_json


  def self.get
    topics = []

    # Main sources:
    # "libération":   251
    # "le figaro":    641,
    # "le monde":     675,
    # "les échos":    684,

    # Get the N lastest stories from each sources
    sources_id = [251, 641, 675, 684]
    sorted_stories = {}

    sources_id.each do |source_id|
      stories = ::AylienAPI::GetStoriesService.new(source_id: source_id,sorted_by: "published_at", per_page: N_LATEST_STORIES).call
      source = stories.first.source.name
      sorted_stories[source] = stories
      # FIXME:
      # Save stories in DB to avoid API recall

    end

    sorted_stories.each do |source, stories|
      puts "#{source} : #{stories.count} articles"
    end

    sorted_stories.each do |source, stories|

      # For each source, find the first story with an hashtag that could get more than 20 stories has a search
      stories.find do |story|
        next if story.hashtags.empty?
        key_words = []
        story.hashtags.each do |hashtag|

          next if hashtag.length < HASHTAGS_MIN_LENGTH || hashtag.length > HASHTAGS_MAX_LENGTH
          next if key_words.size >=  1
          # remove the'#' from the hashtag
          clean_words = hashtag[1..-1]

          # transform 'CamelCase' to 'String with spaces'
          string_words = clean_words.gsub(/([A-ZÉ]+)([A-ZÉ][a-z])/,'\1 \2').gsub(/([a-z\d])([A-ZÉ])/,'\1 \2')

          key_words << string_words
        end

        string_words = key_words.join(' ')

        # Number of results for this search
        results_for_hashtag = ::AylienAPI::GetStoriesService.new(topic_search: string_words).call

        # Keep only stories with at least one hashtag in common
        results_with_common_hashtag = []

        results_for_hashtag.each do |story_canditate|
          common_hashtag = false
          story_canditate.hashtags.each do |hashtag|
            next if common_hashtag
            if story.hashtags.include? hashtag
              common_hashtag = true
            end
          end
          results_with_common_hashtag << story_canditate if common_hashtag
        end

        # Test relevance
        related_stories = results_with_common_hashtag.count
        if related_stories > RELEVANCE_INDEX
          if Topic.pluck(:name).include?(string_words)
            # Topic already exists:
            topic = Topic.find_by_name(string_words)
            if Time.now - Topic.find_by_name(string_words).articles.last.created_at > OBSOLETE_TIME
              # 1.1 topic updated more than 24h ago
                # new search
                topic.new_search
                true
            else
              # 1.2 topic updated less than 24h ago
              # update user from search to hedgy
              topic.user = User.find_by_email("hedgy@hedgenews.eu")
              topic.save
              true
            end
          else
            # create topic

            new_topic = Topic.new(name: string_words)
            new_topic.user = User.find_by_email("hedgy@hedgenews.eu")
            sources_array = new_topic.sort_by_source(results_for_hashtag).keys
            sources_hash = {sources: sources_array}

            new_topic.new_search
            topics << new_topic
            true
          end
        else
          false
        end
      end
    end
    topics
  end


  def sort_by_source(stories)

    stories_by_source = {}

    stories.each do |story|
      if stories_by_source.key? story.source.name
        stories_by_source[story.source.name] << story
      else
        stories_by_source[story.source.name] = [story]
      end

    end
    stories_by_source
  end

  # Oh la belle methode bien longue !
  def new_search
    stories = ::AylienAPI::GetStoriesService.new(topic_search: self.name).call
    unless stories.empty?
      # skip saving article in the topic if the title doesn't have the topic name in it
      topic_words = self.name.split(" ")
      topic_main_words = []
      topic_words.each do |word|
        topic_main_words << word if word.length > 3
      end

      hash_source_url = {}
      stories.each do |story|
        next unless title_include_words?(story.title, topic_main_words)
        next if (story.media[0].url.empty? || story.summary.sentences.join("\n") == "")
        hash_source_url[Source.where(aylien_id: story.source.id.to_i).first.name] = story.links.permalink
      end

      stories.each do |story|
        # do not register an article without image or without abstract to display
        next if (story.media[0].url.empty? || story.summary.sentences.join("\n") == "")
        if Journalist.find_by_aylien_id(story.author.id)
          journalist = Journalist.find_by_aylien_id(story.author.id)
        else
          journalist = Journalist.create!(last_name: story.author.name, aylien_id: story.author.id)
        end
        article = Article.where(aylien_id: story.id).first
        unless article # check if story is already saved as an article in the DB
          article = Article.create!(
                               source_id: Source.where(aylien_id: story.source.id.to_i).first.id,
                               title: story.title,
                               pic_url: story.media[0].url,
                               date: story.published_at,
                               abstract: story.summary.sentences.join("\n"),
                               words_count: story.words_count,
                               aylien_id: story.id,
                               source_url: story.links.permalink,
                               opposite_url: story_opposite_url(story, hash_source_url),
                               journalist_id: Journalist.where(aylien_id: story.author.id).first.id,
                               hashtags: story.hashtags.join(" "),
          )
        end



        if title_include_words?(article.title, topic_main_words)
          # possible that two articles have the same title but not the same source. Change code ? add a condition
          article_id_is_in_topic    = self.articles.pluck(:aylien_id).include?(article.aylien_id)
          article_title_is_in_topic = self.articles.pluck(:title).include?(article.title)
          unless article_id_is_in_topic || article_title_is_in_topic
            self.topic_articles.new(article: article, created_at: Time.current, updated_at: Time.current)
          end
        end
      end

      self.find_image(stories)
      self.sources_json = { sources: hash_source_url.keys }.to_json.gsub("é", "e").gsub("É", "E")
      self.number_sources = JSON.parse(self.sources_json)["sources"].size
    end
    self.save
  end

  def find_image(stories)
    stories.reverse.each do |story|
      if story.media[0].url
        self.image_url = story.media[0].url
        break
      end
      self.image_url = image_path("hedgenews_meta_image")
    end
  end

  def story_opposite_url(story, source_urls)
    # name of the source of the story coming from API
    source_name = Source.where(aylien_id: story.source.id.to_i).first.name

    # find the names - there can be several - of the opposite media to the source of the story
    opposite_media = Article::OPPOSITE_MEDIA[source_name]
    return unless opposite_media

    opposite_media.each do |opposite_medium|
      opposite_url = source_urls[opposite_medium]
      return opposite_url if opposite_url
    end

    return nil
  end

  def title_include_words?(title, words)
    title_words = title.split(" ")
    words.each do |word|
      return false unless title_words.include? word
    end
    true
  end

  def update_number_of_sources
    sources = []
    self.articles.each do |article|
      sources << article.source.name unless sources.include?(article.source.name)
    end
    self.number_sources = sources.count
    self.save
  end

  def update_sources_json
    sources_json = {sources: []}
    self.articles.each do |article|
      sources_json[:sources] << article.source.name unless sources_json[:sources].include?(article.source.name)
    end
    # to check
    self.sources_json = sources_json
    self.save
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include ArticlesHelper

  def index
    @topics = current_user.topics
  end

  def show
    @topic = Topic.find(params[:id])
    @selected_articles = @topic.articles

    @selected_urls = []

    @topic.articles.each do |article|
      @selected_urls << article.source_url
    end
  end

  def create

    @topic = Topic.find_by_name(topic_params[:name])
    @topic.user = current_user
    @topic.save
    redirect_to topics_path
  end

  def edit
    @topic = Topic.find(params[:id])
    @articles = []
    topic_articles =  @topic.topic_articles.order(:created_at).reverse
    topic_articles.each do |topic_article|
      @articles << topic_article.article
    end
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.user = User.find_by_email("search@hedgenews.eu")
    @topic.save
  end

  def publish
    @topic = Topic.find(params[:id])
    @topic.user = User.find_by_email("hedgy@hedgenews.eu")
    @topic.save
    redirect_to root_path
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
  end

  private
  def topic_params
    params.require(:topic).permit(:name)
  end


end

app/views/topics/_topic_card.html.erb
<div class="topic-card topic-card-topics-index">

  <%= link_to topic_path(topic) do %>
    <div class="topic-card-image" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 90%), url('<%= image_path topic.articles.first.pic_url %>')" >

      <h1><%= topic.name %></h1>

    </div>
  <% end %>

  <div class="panel">
    <div class="panel-body">
      <div class="topic-card-legend">
        <p class= "font-header-app"><%= topic.number_sources %> Sources - <%= topic.articles.count %> Articles </p>
        <div class="flex-box-space-around font-header-app" >
          <%= link_to 'Prévisualiser', topic_path(topic) %>
          <%= link_to 'Relancer la recherche', articles_path(topic_search: topic.name) %>
          <%= link_to 'Éditer', edit_topic_path(topic) %>
        </div>
        <br>
        <div class="flex-box-center">
          <%= link_to 'Supprimer', topic_path(topic), class: 'text-blue suppress button-tag font-header-app', method: :patch %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="container">
  <div class = "wrapper-white">
    <div>
      <h2 class="font-header-app">Revue de presse pour "<%= @topic.name %>"</h2>
      <h4 class="font-header-app">
        <span id="number_articles_in_pr" class="font-header-app" data-number="<%= @topic.articles.count %>">
          <%= pluralize(@topic.articles.count, 'article', plural: 'articles')%>
        </span>
        -
        <span id="number_sources_in_pr" class="font-header-app" data-number="<%= @topic.number_sources %>">
          <%= pluralize(@topic.number_sources, 'source', plural: 'sources')%>
        </span>
      </h4>
    </div>
  </div>

  <div class="flex-box-center">
    <%if current_user && current_user.admin %>
      <%= simple_form_for @topic, method: :post, url: publish_topic_path(@topic) do |f| %>
        <%= f.submit 'Publier la revue de presse', class: "btn btn-bordered btn-bordered-primary btn-bordered-primary-on-grey-background"%>
      <% end %>
    <% end %>
  </div>

  <div class="list-group">
    <% @articles.each do |article| %>
      <div class="list-group-item font-header-app">
        <div class='flex-box-space-between'>
          <div class='flex-box-space-between'>
            <div class="image-table">
              <%= link_to article.source_url, target: '_blank' do %>
                <%= image_tag article.pic_url, width:'150px', class: 'image-table' %>
              <% end %>
            </div>
            <div class='logo-title'>
              <%= image_tag "logo/logos_custom/#{article.source.name.gsub('é', 'e').gsub('É', 'E')}-logo-black.png", class: 'table-logo', width: "70px" %>
              <%= link_to article.title, article.source_url, target: '_blank'%>
            </div>
          </div>

          <div class="flex-box-space-between table-buttons">
<!--             <%= link_to 'Haut', class: 'btn btn-bordered btn-bordered-info up' %>
            <%= link_to 'Bas', class: 'btn btn-bordered btn-bordered-info down' %> -->
            <% topic_article = TopicArticle.where(article: article).where(topic: @topic).first %>
            <%= form_tag topic_article_path(topic_article), method: :delete do %>
              <%= hidden_field_tag 'topic_article_id', topic_article.id %>
              <%= submit_tag 'Supprimer', class: 'btn btn-bordered btn-bordered-info suppress' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="flex-box-center">
    <%if current_user && current_user.admin %>
      <%= simple_form_for @topic, method: :post, url: publish_topic_path(@topic) do |f| %>
        <%= f.submit 'Publier la revue de presse', class: "btn btn-bordered btn-bordered-primary btn-bordered-primary-on-grey-background"%>
      <% end %>
    <% end %>
  </div>

  <div class="container text-center">
    <%= link_to topics_path do %>
      <%= image_tag "icone/rewind.FF682F.png", class: 'image-small' %>
    <%end%>
  </div>

</div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function(){

      $('.suppress').click( function() {
        var nbarticle = $('#number_articles_in_pr').data('number');
        nbarticle = nbarticle - 1;
        $('#number_articles_in_pr').data('number', nbarticle);
        $(this).closest('.list-group-item').fadeOut('slow', function(){
          $(this).remove();
        });
        $('#number_articles_in_pr').html(nbarticle + " article(s)");
      });

      $('.up').click( function() {
        $row = $(this).closest('.list-group-item')
        function moveUp($row) {
          $before = $row.prev();
          $row.insertBefore($before);
        }
      });

    })
  </script>
<% end %>

app/views/topics/index.html.erb
<div class="container">
  <div id="search-wrapper" class="wrapper-white">
    <div>
      <% if @topics.empty? %>
        <h2 class="font-header-app">Vous n'avez pas encore créé de revues de presse</h2>
        <h4 class= "font-header-app">Faites une recherche pour trouver des sujets intéressants, que vous pourrez ajouter à cette section :</h4>
        <%= render 'shared/search_bar', value: "" %>
      <% else %>
        <h2 id="number_topics_bookmarked", class="font-header-app"><%= pluralize(@topics.count, 'revue de presse sauvegardée', plural: 'revues de presse sauvegardées')%></h2>
        <div class="topics_bookmarked" data-number="<%= @topics.count %>"></div>
      <%end%>
    </div>
  </div>

  <div class="flex-box-center">
    <%if current_user %>
      <a href="#" id="create-press-review" class="btn btn-bordered btn-bordered-primary btn-bordered-primary-on-grey-background">Créer une nouvelle revue de presse</a>
    <% end %>
  </div>

  <div class="row" >
    <div class="col-xs-12">
      <div id="search-bar-create-topic" class="flex-box-space-around catchline padding-home-search-bar wrapper-white font-header-app hidden">
        <%= render 'shared/search_bar', value: nil %>
      </div>
    </div>
  </div>

  <div class="row">
    <% @topics.order(:created_at).reverse.each do |topic| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= render 'topic_card', topic: topic %>
      </div>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function(){

      // Delete bookmarked topic on click
      $('.suppress').click( function() {
        var nbtopic = $('.topics_bookmarked').data('number')
        nbtopic = nbtopic - 1;

        $('.topics_bookmarked').data('number', nbtopic);

        $(this).closest('.topic-card').fadeOut('slow', function(){
          $(this).remove();
        });
        $('#number_topics_bookmarked').html(nbtopic + " revue(s) de presse sauvegardée(s)");
      });


      // Make search bar appear when create press review button clicked
      $("#create-press-review").click(function(e){
        $("#search-bar-create-topic").removeClass("hidden");
      });
    })
  </script>
<% end %>

app/views/topics/show.html.erb
<% if @topic.articles.empty? %>

  <div class='container'>
    <div class="flex-box-space-around catchline wrapper-white font-header-app">
      <div>
        <h2 class= "font-header-app">Aucun article dans la revue de presse <em><%= @topic.name %></em>.</h2>
        <h4 class= "font-header-app">Faites une recherche pour trouver des articles intéressants, que vous pourrez ajouter à votre revue de presse :</h4>
        <%= render 'shared/search_bar', value: "" %>
      </div>
    </div>
    <%= link_to root_path do %>
      <%= image_tag "icone/hedgenews_logo.FF682F.png", class: "animate-logo" %>
    <%end%>
  </div>

<% else %>
  <div class="container">
    <div class="flex-box-space-around font-header-app">
      <div id="search-wrapper" class="wrapper-white">
        <div>
          <h2 class="font-header-app"><%= pluralize(@topic.articles.count, 'article selectionné', plural: 'articles sélectionnés')%> pour la revue de presse sur <em>"<%= @topic.name %>"</em></h2>
        </div>
      </div>
    </div>
    <div class="flex-box-center">
      <a href="#" class="btn btn-bordered btn-bordered-primary btn-bordered-primary-on-grey-background open-all">Lire tous les articles complets</a>
      <%= content_tag :div, class: "selected_urls", data: {url: @selected_urls} do %>
      <% end %>
    </div>
    <br>
    <div class="flex-box-center" >
      <div id="search-wrapper">
        <%= render 'shared/index_articles', value: @selected_articles %>
      </div>
    </div>
  </div>


  <div class="container text-center">
    <%= link_to topics_path do %>
      <%= image_tag "icone/rewind.FF682F.png", class: 'image-small' %>
    <%end%>
  </div>

<% end %>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function(){

      window.scroll(0, 60);

      $('#topic_search').click(function(){
        $(this).val("");
      });

      $('a.open-all').click(function(e) {
        e.preventDefault();
        $('.selected_urls').data('url').forEach(function(url_source) {
          setTimeout(function() {}, 1000);
          window.open(url_source);
          self.focus();
          // if(!win){
          //   //Broswer has blocked it
          //   alert('Please allow popups for this site');
          // }
        });
      });

      $('.press-review-title').click(function(e) {
        setTimeout(function() {}, 10);
        $(this).closest('.dropdown-menu').fadeOut('slow', function(){
          $(this).hide();
        });
      });

    })
  </script>
<% end %>