config/routes.rb
Rails.application.routes.draw do
  mount LetsencryptHttpChallenge::Engine => "/" unless ENV['LE_HTTP_CHALLENGE_RESPONSE'].blank?
  
  devise_for :users

  resources :article_bookmarks, only: [:index]

  root to: 'pages#home'

  resources :articles, only: [:index, :destroy]

  resources :topics do
    member do
      post :publish
    end
  end

  post 'topic_article', to: 'topic_articles#create'
  delete 'topic_article', to: 'topic_articles#destroy'

  post 'bookmark', to: 'article_bookmarks#create'
  delete 'bookmark', to: 'article_bookmarks#destroy'

  # Styleguide
  get 'styleguide', to:'pages#styleguide'

  get 'team', to: 'pages#team'

  get 'about', to: 'pages#about'

  # Test api aylien
  get 'search', to: 'aylien_tests#search'
  get 'results', to: 'aylien_tests#results'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible font-header-app" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible font-header-app" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>

<div class="footer-hedge">

    <div><%= link_to "L'Équipe", team_path, class: "footer-hedge-item" %>
    </div>

    <div><%= link_to "Notre démarche", about_path, class: "footer-hedge-item" %>
    </div>

    <!-- Logo -->
    <a href="/" class="footer-hedge-brand">
      <%= image_tag "icone/hedgenews_logo.black.png"%>
    </a>


</div>

</footer>

app/views/shared/_index_articles.html.erb
  <div class='container'>
    <div class='row-fix'>
      <% @selected_articles.each do |article| %>
        <div class='card'>

          <h3><%= link_to article.source_url, target: '_blank' do %></h3>
            <div class='image-article-card'>
              <% unless article.pic_url.empty?%>
                <%= image_tag article.pic_url %>
              <% end %>
            </div>
          <% end %>

          <div class="panel article-panel card-body">


            <div class="panel-heading">

              <div class="flex-box-space-between align-items-center">
                <div class="flex-box-space-between">
                  <%= image_tag "logo/logos_custom/#{article.source.name.gsub('é' ,'e').gsub('É' ,'E')}-logo-black.png", width: "80px" %>
                </div>

                  <div class="flex-box-space-between">
                    <% if current_user %>
                      <% unless current_user.topics.empty? %>
                        <div>
                          <div class="navbar-wagon-item font-header-app">
                            <div class="dropdown">
                              <div>
                               <%= image_tag "icone/add-review.png", id: "navbar-wagon-menu", height: '40px', data: { toggle: "dropdown"} %>
                                <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu dropdown-press-review-ul">
                                  <li class="dropdown-press-review-li">Ajouter l'article à une revue de presse :</li>
                                  <hr>
                                  <% current_user.topics.order(:created_at).reverse.each do |topic| %>
                                    <li class="dropdown-press-review-li">
                                      <%= form_tag topic_article_path, method: :post, id: 'article' do %>
                                        <% if current_user.articles.include?(Article.find_by_aylien_id(article.aylien_id)) %>
                                          <%= hidden_field_tag "article[id]", article.id %>
                                        <% else %>
                                          <%= hidden_field_tag "article[id]", article.id %>
                                        <% end %>
                                        <%= hidden_field_tag "topic[id]", topic.id %>
                                        <%= button_tag topic.name, class: 'red-hover button-tag press-review-title'%>
                                      <% end %>
                                    </li>
                                  <% end %>
                                </ul>
                              </div>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    <% end %>

                    <div>
                      <% if current_user %>
                        <div class="bookmark_form_container" data-story-id="<%= article.aylien_id %>">
                          <% if current_user.articles.include?(Article.find_by_aylien_id(article.aylien_id)) %>
                            <%= render 'articles/unbookmark_form', article: article %>
                          <% else %>
                            <%= render 'articles/bookmark_form', article: article, hash_source_url: @hash_source_url %>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>

              <h3 class="article-title"><%= link_to article.title, article.source_url, target: '_blank' %></h3>
              <h6>Publié il y a <%= distance_of_time_in_words(article.date, Time.now) %> <% if article.journalist.last_name != "" %>par <%= article.journalist.last_name %><% end %></h6>
              <% if article.hashtags && article.hashtags != " " && article.hashtags != ""%>
                <ul class= "list-inline">
                  <li>
                    <% article.hashtags.split(" ").each_with_index do |hashtag, index| %>
                      <% next if index > 4%>
                      <span class="hashtag"><%= hashtag %></span>
                    <% end %>
                  </li>
                </ul>
              <% end %>
              <ul class= "list-inline">
                <li><i class="fa fa-clock-o" aria-hidden="true"></i></li>
                <li><h6><%= time_to_read(article.words_count) %></h6></li>
              </ul>
            </div>

            <div class="panel-body">
              <p><%= article.abstract %></p>
            </div>


            <div class="panel-body">
              <h6><strong>Contexte :</strong></h6>
              <% if ["Le Monde", "Le Figaro", "Le Point"].include?(article.source.name) %>
                <h6>A propos du <%= article.source.name.split(" ").last %></strong></h6>
              <% elsif ["Les Échos"].include?(article.source.name) %>
                <h6>A propos des <%= article.source.name.split(" ").last %></strong></h6>
              <% else %>
                <h6>A propos de <%= article.source.name %></strong></h6>
              <% end %>
              <%= raw(article.source.presentation) %>
            </div>

            <div class="flex-box-center">
              <%= link_to "Lire l'article complet", article.source_url, class: "btn btn-bordered btn-bordered-info", target: '_blank' %>
              <%= link_to "Découvrir une opinion différente", article.opposite_url, class: "btn btn-bordered btn-bordered-primary" , target: '_blank'%>
            </div>

          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed flex-box-space-between">
  <div class="flex-item">
    <%= render 'shared/search_bar_in_navbar' %>
  </div>

    <!-- logo -->
  <div class="flex-body">
    <div class="navbar-wagon-logotype">
        <a href="/" class="navbar-wagon-brand text-center">
          <h2 class= "navbar-hedgenews">
            <%= image_tag "icone/hedgenews_logo.black.png" %>
            HedgeNews
          </h2>
        </a>
    </div>
  </div>

    <div class="flex-item">
      <div class="flex-box-right">
      <!-- Right navigation-->
      <div class="navbar-wagon-right">
          <!-- Button (call-to-action) -->
        <div class='sub-navbar'>
          <% if current_user %>
            <%= link_to 'Mes Revues de presse', topics_path, class: "navbar-wagon-item navbar-wagon-link font-oswald blue-hover" %>
            <%= link_to 'Mes Favoris', article_bookmarks_path, class: "navbar-wagon-item navbar-wagon-link font-oswald blue-hover" %>
            <!-- Profile picture and dropdown -->
            <div class="navbar-wagon-item">
              <div class="dropdown font-header-app">
               <i class="fa fa-user-o" aria-hidden="true" id= "navbar-wagon-menu" data-toggle="dropdown"></i>
                <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                  <li><%= link_to 'Mon compte', edit_user_registration_path, class: "red-hover font-header-app" %></li>
                  <li><%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: "font-header-app"%></li>
                </ul>
              </div>
            </div>
              <%else%>
                <%= link_to 'Se connecter', new_user_session_path, class: "navbar-wagon-item  btn btn-bordered btn-bordered-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>
  <!-- Right Navigation -->
<div class="container">
  <div class="navbar-wagon-second hidden-xs hidden-sm font-oswald">
    <div>
      En ce moment :
      <% @topics_nav.each do |topic| %>
        <%= link_to topic.name.capitalize, articles_path(topic_search: topic.name), class: "navbar-wagon-item navbar-wagon-link red-hover" %>
      <% end %>
    </div>

<!-- Notification link-->
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    </a> -->


    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
    $searchWrapperHeightOffset      = $("#search-wrapper").offset().top; // 180
    $searchWrapperHeight            = $("#search-wrapper").height();     // 155
    $heightToMakeNavSearchBarAppear = $searchWrapperHeightOffset + $searchWrapperHeight
    $(window).scroll(function(e){
      $scrollSpyHeight = $(this).scrollTop();
      if ($scrollSpyHeight > $heightToMakeNavSearchBarAppear) {
        $("#navbar-search").removeClass("hidden");
      } else {
        $("#navbar-search").addClass("hidden");
      };
    });
  </script>
<% end %>

app/views/shared/_search_bar.html.erb
<div class="search-bar">
  <%= form_tag(articles_path, method: "get") do %>
    <div>
      <%= text_field_tag :topic_search, nil, class: 'font-header-app', placeholder: "", required: true, value: value  %>
      <%= button_tag "", class: "search-button icon" do %>
        <%= image_tag "icone/loupe.png" %>
      <%end%>
    </div>
  <% end %>
</div>

app/views/shared/_search_bar_in_navbar.html.erb
<div class="search-bar-xs <%= hidden_bar_class %>" id="<%= hidden_bar_id%>">
  <%= form_tag(articles_path, method: "get") do %>
    <div>
      <%= text_field_tag :topic_search, nil, placeholder: "", required: true, value: @topic_search, id: "topic-search-navbar" %>
      <%= button_tag "", class: "search-button" do %>
        <%= image_tag "icone/loupe.png", id: "loupe-navbar" %>
      <% end %>
    </div>
  <% end %>
</div>