config/routes.rb
Rails.application.routes.draw do
  mount LetsencryptHttpChallenge::Engine => "/" unless ENV['LE_HTTP_CHALLENGE_RESPONSE'].blank?
  
  devise_for :users

  resources :article_bookmarks, only: [:index]

  root to: 'pages#home'

  resources :articles, only: [:index, :destroy]

  resources :topics do
    member do
      post :publish
    end
  end

  post 'topic_article', to: 'topic_articles#create'
  delete 'topic_article', to: 'topic_articles#destroy'

  post 'bookmark', to: 'article_bookmarks#create'
  delete 'bookmark', to: 'article_bookmarks#destroy'

  # Styleguide
  get 'styleguide', to:'pages#styleguide'

  get 'team', to: 'pages#team'

  get 'about', to: 'pages#about'

  # Test api aylien
  get 'search', to: 'aylien_tests#search'
  get 'results', to: 'aylien_tests#results'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/aylien_tests_controller.rb
class AylienTestsController < ApplicationController

  def search
  end

  def results
    @topic_search = params[:topic_search]
    @stories = ::AylienAPI::GetStoriesService.new(topic_search: @topic_search).call
  end
end

app/views/aylien_tests/results.html.erb
<h1>Articles trouvés pour <em><%= @topic_search %></em></h1>

<% @stories.each do |story| %>
  <div class="panel">
    <div class="panel-heading">
      <h1><%=story.title %></h1>
      <h2><%=story.source.name %> (<%= story.source.id%>)</h2>
      <p>Publié le <%= story.published_at %> par <strong><%= story.author.name %></strong></p>
      <p><%= story.words_count %> mots</p>
      <div class="list-inline">
        <%= link_to "source", story.links.permalink %>
      </div>
    </div>
    <div class="panel-body">
      <p><%=story.summary.sentences.join("\n") %></p>
      <!-- <p><%= story.body %></p> -->
    </div>
  </div>
<% end %>

app/views/aylien_tests/search.html.erb
<div class="container">
  <br><br>
  <div class="panel">
    <div class="panel-body text-center">
        <%= form_tag(results_path, method: "get") do %>
          <%= label_tag :topic_search, "Sujet" %>
          <%= text_field_tag :topic_search, nil, placeholder: "Rechercher un sujet", require: true %>
          <%= button_tag "Recherche", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>